### ISSUE TITLE
wm.get_config() does not return all parameters

### ISSUE THREAD

**Issue by jkobject** [broadinstitute/dalmatian#16]
It does display some optional inputs but not all of them..

tried with `wm.get_config("gatk","CNV_Somatic_Panel_Workflow")`

the function seems to do a lot of post processing of the request response..
I don't know what might be causing it. 

Best,
:)

**Comment by agraubert** [comment]
Could you give us some information about the environment and the configuration?

1. What version of dalmatian are you using? It's internals have changed dramatically recently
2. Can you provide the method configuration that dalmatian is showing
3. Can you provide the method configuration in Firecloud/Terra that you expect to see?

Edit: The [API Call used](https://api.firecloud.org/#!/Method_Configurations/getWorkspaceMethodConfig) does not include inputs which are not currently set. This is expected behavior for that endpoint. To get the full template for a method, you should use the [Method IO](https://api.firecloud.org/#!/Method_Repository/getMethodIO) endpoint and merge its output with your configuration. This behavior currently exists in the Lapdog UI, but it can be backported, if it's something you would like to see in Dalmatian

**Comment by jkobject** [comment]
yeah I had version 0.0.2 for some reasons. just upgraded to last version. now every params are here. 
Thx!
