### ISSUE TITLE
New WorkspaceManager constructor incompatible

### ISSUE THREAD

**Issue by julianhess** [broadinstitute/dalmatian#24]
The old WorkspaceManager constructor signature (as described in the readme) was

```dalmatian.WorkspaceManager(<namespace>, <workspace>)```

However, [this commit](https://github.com/broadinstitute/dalmatian/blame/f7286239954f63f5770634259fb3d52f8e3172c1/dalmatian/wmanager.py#L119) changed the signature to `WorkspaceManager("<namespace>/<workspace>")`. This breaks a lot of old scripts that were expecting the old signature.

Would it be possible to revert this @agraubert ?

**Comment by agraubert** [comment]
François and I discussed this at length and ultimately decided that the merged "namespace/name" reference format would become the new standard in the API. This was an intentional breaking change, but as you point out, it was not updated in the Readme. I have fixed the readme in 6c824a1

The new reference format is also used when referencing methods and configurations.
